name: example
description: example to descibe the totaljs_flutter library

environment:
  sdk: ^3.6

dependencies:
  device_info_plus: ^11.1.0
  flutter:
    sdk: flutter

  http: ^1.2.2
  totaljs_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
