name: totaljs_flutter
version: 1.0.10
homepage: https://reemax.io/totaljs_flutter
repository: https://github.com/mikebaumgart/total.js_flutter
issue_tracker: https://github.com/mikebaumgart/total.js_flutter/issues
description: Total.js + Flutter

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  device_info_plus: ^11.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
